name: Build (macOS Intel)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Show repo layout
        run: |
          pwd
          ls -la
          /usr/bin/find . -maxdepth 2 -print
      - name: Install SDL2
        run: |
          brew update
          brew install sdl2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release -j
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wave-player-macos-intel
          path: |
            build/wave_player
            build/wave-player.app
          if-no-files-found: warn
